const languageCodes = {
  en: "English",
  zh: "Chinese",
  es: "Spanish",
  fr: "French",
  de: "German",
  ja: "Japanese",
  ko: "Korean",
  ru: "Russian",
  pt: "Portuguese",
  it: "Italian",
  ar: "Arabic",
  hi: "Hindi",
  nl: "Dutch",
  el: "Greek",
  he: "Hebrew",
  tr: "Turkish",
  th: "Thai",
  sv: "Swedish",
  pl: "Polish",
  vi: "Vietnamese",
  id: "Indonesian",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  cs: "Czech",
  hu: "Hungarian",
};

export default languageCodes;
